### PR TITLE
Blob support, PORT environment variable and dockerfile optimizations.

### PR DESCRIPTION
**Pull request by karhig**

### CODE REVIEW

**Comment by karhig** [comment]
This is really more node programming than I'm comfortable with, it's definitely worth checking my changes for correctness.

**Comment by masumsoft** [comment]
@karhig blob and port support looks fine to me, but didn't get the reason behind the replacement of batch queries with parallel promises. Batches should be more performant in my opinion.

**Comment by karhig** [comment]
@masumsoft The primary reason was that our blobs were bigger than the batch limit, so I got errors.

The secondary reason is discussed in the article I linked to. As I understand things, batches shouldn't be used for performance reasons as they take away some of cassandras ability to optimize over multiple nodes and partitions. I'm quite new to Cassandra, so I can't be sure that's correct.

**Comment by masumsoft** [comment]
The exporter was meant to be used for development purposes, where a multi node cluster would be unlikely and thus this used an unlogged batch. 

Anyways it's more important to be robust instead of minor performance improvements and for a multi node cluster batches are not a good thing. Blobs types was not tested and seems like a good fix. So merging it, thanks for the PR.

**Pull request merged**
